"""Recreate contract_sla with String id

Revision ID: 7d5c081bbec6
Revises: 9a1bfb9010e4
Create Date: 2026-03-27 11:30:54.878410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5c081bbec6'
down_revision: Union[str, Sequence[str], None] = '9a1bfb9010e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
