"""Initial schema

Revision ID: 9a1bfb9010e4
Revises: 
Create Date: 2026-03-27 10:37:29.009614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1bfb9010e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('doc_status', sa.String(length=50), nullable=False),
    sa.Column('dealer_offer_name', sa.String(length=255), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_sla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('apr_percent', sa.Float(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('monthly_payment', sa.Float(), nullable=True),
    sa.Column('down_payment', sa.Float(), nullable=True),
    sa.Column('early_termination_fee', sa.Float(), nullable=True),
    sa.Column('mileage_allowance_yr', sa.Integer(), nullable=True),
    sa.Column('red_flags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_sla_id'), 'contract_sla', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_sla_id'), table_name='contract_sla')
    op.drop_table('contract_sla')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
