"""Add Contract ↔ ContractSLA relationship

Revision ID: bbbd85a2cb1f
Revises: 7d5c081bbec6
Create Date: 2026-03-27 14:16:11.662341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbd85a2cb1f'
down_revision: Union[str, Sequence[str], None] = '7d5c081bbec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
